name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装项目的依赖


      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/<your-heroku-app>.git  # 将 `<your-heroku-app>` 替换为您的 Heroku 应用名称
          git push heroku main  # 推送到 Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 

