name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '*/10 8-22 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://yizhang527-streamlit-portfolio-portfolio-mkl3x5.streamlit.app/ || true
          echo "App pinged at $(date)"
